from __future__ import annotations

OPERATIONAL_CALMNESS = "OPERATIONAL_CALMNESS"
ADVISORY_OVER_AUTOMATION = "ADVISORY_OVER_AUTOMATION"
DETERMINISTIC_PUBLISH_PATH = "DETERMINISTIC_PUBLISH_PATH"
BOUNDED_COMPLEXITY = "BOUNDED_COMPLEXITY"
FAIL_OPEN_GOVERNANCE = "FAIL_OPEN_GOVERNANCE"
HUMAN_ACCOUNTABLE_EDITORIAL = "HUMAN_ACCOUNTABLE_EDITORIAL"
MINIMAL_RUNTIME_SURFACE = "MINIMAL_RUNTIME_SURFACE"
QUIET_HEALTHY_OPERATIONS = "QUIET_HEALTHY_OPERATIONS"
NO_SELF_MODIFYING_BEHAVIOR = "NO_SELF_MODIFYING_BEHAVIOR"

ALL_PRINCIPLES: tuple[str, ...] = (
    OPERATIONAL_CALMNESS,
    ADVISORY_OVER_AUTOMATION,
    DETERMINISTIC_PUBLISH_PATH,
    BOUNDED_COMPLEXITY,
    FAIL_OPEN_GOVERNANCE,
    HUMAN_ACCOUNTABLE_EDITORIAL,
    MINIMAL_RUNTIME_SURFACE,
    QUIET_HEALTHY_OPERATIONS,
    NO_SELF_MODIFYING_BEHAVIOR,
)

ALIGNED = "ALIGNED"
AT_RISK = "AT_RISK"
DRIFTING = "DRIFTING"
