from __future__ import annotations

from typing import Any


def subsystem_contracts() -> dict[str, dict[str, Any]]:
    """Authoritative operational contracts — boundaries, not implementation."""
    return {
        "runtime": {
            "owner": "bot/observability, bot/runtime",
            "inputs": ["loop heartbeats", "queue depth", "env profile"],
            "outputs": ["runtime_state", "soft_degraded", "loop_health metrics"],
            "persistence": ["runtime_state_snapshot", "ops_runtime_baseline"],
            "side_effects": ["ingestion pause", "autonomous_passive"],
            "failure_behavior": "fail-open; soft degrade via evaluate_soft_degradation",
            "scheduling": "watchdog interval + loop registry",
        },
        "resilience": {
            "owner": "bot/ops_resilience",
            "inputs": ["observation_pulse", "dependency probes", "failure budgets"],
            "outputs": ["posture", "backpressure flags", "operator guidance"],
            "persistence": ["ops_resilience_state", "ops_resilience_events", "ops_resilience_daily"],
            "side_effects": ["defer analytics", "suspend archival", "publish throttle"],
            "failure_behavior": "fail-open; never block publish",
            "scheduling": "OPS_RESILIENCE_INTERVAL_SEC background loop",
        },
        "lifecycle": {
            "owner": "bot/ops_lifecycle",
            "inputs": ["retention policies", "db size", "pulse archives"],
            "outputs": ["compaction", "archive bundles", "storage report"],
            "persistence": ["ops_lifecycle_runs", "ops_lifecycle_daily", "var/archives"],
            "side_effects": ["row prune", "optional vacuum"],
            "failure_behavior": "fail-open; skip when resilience suspends archival",
            "scheduling": "OPS_LIFECYCLE_INTERVAL_SEC",
        },
        "trust_calibration": {
            "owner": "bot/trust_calibration",
            "inputs": ["publish traces", "operator ratings", "warning outcomes"],
            "outputs": ["subsystem trust bands", "agreement metrics"],
            "persistence": ["ops_trust_calibration_events", "ops_trust_subsystem_daily"],
            "side_effects": "none on publish path",
            "failure_behavior": "fail-open",
            "scheduling": "on publish + operator rating + /trust_calibration",
        },
        "editorial_memory": {
            "owner": "bot/editorial/memory",
            "inputs": ["published headlines", "topics", "entities"],
            "outputs": ["storylines", "contradiction warnings", "saturation"],
            "persistence": ["editorial_storylines", "editorial_story_events"],
            "side_effects": "preview warnings only",
            "failure_behavior": "fail-open",
            "scheduling": "post-publish background",
        },
        "prioritization": {
            "owner": "bot/editorial/priority",
            "inputs": ["pending queue", "momentum", "memory context"],
            "outputs": ["priority scores", "ranked queue", "drift alerts"],
            "persistence": ["editorial_priority_scores", "editorial_priority_daily"],
            "side_effects": "preview + /priority_queue only",
            "failure_behavior": "fail-open",
            "scheduling": "post-publish + on-demand",
        },
        "operator_ux": {
            "owner": "bot/operator_ux",
            "inputs": ["pulse", "priority drift", "attention signals"],
            "outputs": ["digest", "attention queue", "enhanced dashboard"],
            "persistence": ["ops_attention_log", "ops_attention_daily"],
            "side_effects": "Telegram delivery (deduped, quiet hours)",
            "failure_behavior": "fail-open",
            "scheduling": "on-demand commands",
        },
        "evidence_review": {
            "owner": "bot/ops_evidence",
            "inputs": ["7d telemetry", "trust snapshots", "forensics"],
            "outputs": ["weekly review", "tuning suggestions", "noise candidates"],
            "persistence": ["ops_evidence_reviews"],
            "side_effects": "none",
            "failure_behavior": "fail-open",
            "scheduling": "weekly script + /weekly_review",
        },
        "observation": {
            "owner": "bot/ops_observation",
            "inputs": ["health HTTP", "loop health", "publish stats"],
            "outputs": ["observation_pulse", "anomalies", "var/ops/pulses"],
            "persistence": ["var/ops/daily", "var/ops/pulses"],
            "side_effects": "none",
            "failure_behavior": "fail-open",
            "scheduling": "watchdog + daily snapshot script",
        },
        "publish_flow_health": {
            "owner": "bot/editorial/flow_health",
            "inputs": ["ingestion outcomes", "publish guard verdicts", "funnel counters"],
            "outputs": [
                "starvation advisory",
                "bounded adaptive thresholds",
                "coverage score",
                "diversity gates",
                "relaxation budget telemetry",
            ],
            "persistence": [
                "ops_publish_funnel_hourly",
                "ops_flow_health_state",
                "ops_duplicate_escape_log",
            ],
            "calibration": [
                "rhythm smoothing",
                "category balance recovery nudge",
                "digest discipline",
                "predictability score",
                "newsroom mode classification",
            ],
            "governance": [
                "baseline deviation tracking",
                "signal compression",
                "config pressure",
                "surge rhythm balance",
                "warning fatigue",
                "operator trust index",
            ],
            "vitality": [
                "editorial vitality score",
                "stagnation risk",
                "novelty pressure",
                "medium-cycle responsiveness",
                "long-tail protection",
                "operational realism index",
            ],
            "durability": [
                "graceful degradation modes",
                "heuristic influence visibility",
                "adaptive state hygiene",
                "baseline immunity",
                "low-observability survival",
                "operational simplicity index",
                "weekly self-audit",
            ],
            "slimming": [
                "heuristic consolidation analysis",
                "config surface scoring",
                "telemetry pruning",
                "adaptive state minimization",
                "change risk map",
                "operational core map",
            ],
            "reliability": [
                "freeze discipline",
                "survivability self-checks",
                "runtime fatigue",
                "telemetry collapse protection",
                "recovery envelope validation",
                "operator absence resilience",
                "operational maturity index",
            ],
            "rehearsal": [
                "survivability rehearsal profiles",
                "uptime stability validation",
                "drift boundary governance",
                "recovery calmness",
                "maintenance readiness",
                "core freeze candidacy",
            ],
            "certification": [
                "stabilization freeze governance",
                "operational evidence summaries",
                "configuration lockdown analysis",
                "change moratorium pressure",
                "operational confidence index",
                "maintenance-mode readiness",
                "operational certification candidacy",
            ],
            "freeze_registry": [
                "operational surface classification",
                "controlled evolution ledger",
                "drift exposure index",
                "stewardship horizon estimate",
                "ultra-quiet digest mode",
            ],
            "operational_memory": [
                "operational signatures",
                "bounded incident memory",
                "recovery archetypes",
                "institutional calmness index",
                "recurrence detection",
            ],
            "doctrine": [
                "operational constitution",
                "doctrine drift detection",
                "stewardship constitution score",
                "complexity continuity",
                "institutional stewardship mode",
            ],
            "strategic_resilience": [
                "sustainability dimensions",
                "architectural erosion detection",
                "strategic resilience index",
                "sustainability horizon",
                "stewardship fatigue",
                "bounded sustainability memory",
            ],
            "minimalism": [
                "governance redundancy detection",
                "architectural compression score",
                "operational entropy accumulation",
                "compression candidates",
                "quiet infrastructure continuity",
                "invisible digest mode",
            ],
            "closure": [
                "architectural sufficiency",
                "governance saturation index",
                "expansion pressure detection",
                "steady-state continuity",
                "operational closure candidacy",
            ],
            "legacy": [
                "stewardship dependency risk",
                "operational legibility index",
                "succession readiness",
                "institutional transferability",
                "bounded legacy memory",
            ],
            "observability": [
                "governance cohesion status",
                "observability integrity index",
                "canonical governance propagation verification",
                "observability drift detection",
                "canonical truth continuity",
                "bounded observability digest",
            ],
            "convergence": [
                "governance convergence detection",
                "stewardship recursion detection",
                "governance finalization index",
                "stewardship novelty decay",
                "convergence continuity",
                "governance finalization candidacy",
                "bounded convergence digest",
            ],
            "runtime_validation": {
                "owner": "bot/editorial/runtime_validation",
                "inputs": ["metrics_json", "collector ctx", "loop registry snapshot"],
                "outputs": [
                    "persistence aging verification",
                    "digest silence verification",
                    "scheduler survivability",
                    "telemetry stability",
                    "restart survivability",
                    "operational aging summary",
                    "weekly operational baseline capture",
                ],
                "persistence": "read-only metrics_json inspection",
                "side_effects": "none",
                "failure_behavior": "fail-open",
                "scheduling": "on-demand snapshot only",
            },
            "side_effects": "relaxed dedupe/cluster/guard when starving within budget + hysteresis",
            "failure_behavior": "fail-open",
            "scheduling": "inline on ingest/publish + digest scheduler recovery hook",
        },
        "forensics": {
            "owner": "bot/ops_forensics",
            "inputs": ["timeline events", "audit actions", "runtime snapshots"],
            "outputs": ["incident timeline", "bundles", "drift warnings"],
            "persistence": ["live_incident_timeline", "live_operational_audit"],
            "side_effects": "append-only logging",
            "failure_behavior": "fail-open",
            "scheduling": "hooks + runtime_snapshot_loop",
        },
    }
